name: CI-API
on: [push, pull_request]

jobs:
  build-api:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: '~/.pnpm-store'
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: corepack enable
      - run: corepack prepare pnpm@6.22.2 --activate

      - name: Install dependencies
        run: |
          pnpm install --shamefully-hoist --filter=mixstream-shared --filter=mixstream-api

      - name: Build API
        run: |
          pnpm build --filter=mixstream-shared --filter=mixstream-api --stream

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: (!startsWith(github.ref, 'refs/pull/'))

      - name: Login to Harbor
        uses: docker/login-action@v1
        if: (!startsWith(github.ref, 'refs/pull/'))
        with:
          registry: hub.agoralab.co
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        if: (!startsWith(github.ref, 'refs/pull/'))
        with:
          context: .
          push: true
          tags: hub.agoralab.co/rdc/mixstream-api:latest
